#!/usr/bin/env python3
"""Apply released OneDrive share links from the maintainer queue CSV."""

from __future__ import annotations

import argparse
import csv
import sys
from datetime import date
from pathlib import Path

from check_public_link_release_queue import QueueUpdate, collect_queue_updates
from materialize_folder_bundles_to_onedrive import ONEDRIVE_ROOT
from resource_manifest import MANIFEST_PATH, REPORT_DIR, read_manifest, write_manifest

DEFAULT_QUEUE = REPORT_DIR / "public_link_release_queue.csv"
RESULTS_CSV = REPORT_DIR / "public_link_release_results.csv"
RESULTS_MD = REPORT_DIR / "public_link_release_results.md"
ONEDRIVE_RELEASE_LOG = ONEDRIVE_ROOT / "MANIFESTS" / "public_link_release_log.md"


def write_results(updates: list[QueueUpdate], resources_by_id: dict[str, dict[str, object]]) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "id",
        "title",
        "course",
        "contributor",
        "public_url_status",
        "public_url",
        "public_link_released_at",
        "error",
    ]
    rows: list[dict[str, str]] = []
    for update in updates:
        resource = resources_by_id[update.rid]
        rows.append(
            {
                "id": update.rid,
                "title": str(resource["title"]),
                "course": str(resource["course"]),
                "contributor": str(resource["contributor"]),
                "public_url_status": "released",
                "public_url": update.url,
                "public_link_released_at": update.released_at,
                "error": "",
            }
        )
    with RESULTS_CSV.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    lines = [
        "# Public Link Release Results",
        "",
        "Generated by `scripts/apply_public_link_release_queue.py`.",
        "",
        "| ID | Course | Contributor | Status | Public URL | Error |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| `{row['id']}` | {row['course']} | {row['contributor']} | {row['public_url_status']} | {row['public_url']} | {row['error']} |"
        )
    RESULTS_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def append_onedrive_release_log(updates: list[QueueUpdate]) -> None:
    if not updates:
        return
    ONEDRIVE_RELEASE_LOG.parent.mkdir(parents=True, exist_ok=True)
    if not ONEDRIVE_RELEASE_LOG.exists():
        ONEDRIVE_RELEASE_LOG.write_text("# Public Link Release Log\n\n", encoding="utf-8")
    with ONEDRIVE_RELEASE_LOG.open("a", encoding="utf-8") as fh:
        fh.write(f"\n## {date.today().isoformat()} manual queue release\n\n")
        for update in updates:
            fh.write(f"- `{update.rid}` released {update.released_at} -> {update.url}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--queue", type=Path, default=DEFAULT_QUEUE, help="CSV queue with public_url_to_fill values.")
    parser.add_argument("--execute", action="store_true", help="Write updates into the resource manifest.")
    parser.add_argument("--allow-released", action="store_true", help="Allow filled rows to replace already released links.")
    args = parser.parse_args()

    resources = read_manifest()
    by_id = {str(resource["id"]): resource for resource in resources}
    updates, errors = collect_queue_updates(
        args.queue,
        resources,
        allow_released=args.allow_released,
    )

    if errors:
        print("\n".join(errors))
        return 1
    if not updates:
        print(f"No public_url_to_fill values found in {args.queue}")
        return 0

    for update in updates:
        resource = by_id[update.rid]
        print(f"{'UPDATE' if args.execute else 'PLAN'} {update.rid}: {update.url}")
        if args.execute:
            resource["public_url"] = update.url
            resource["public_url_status"] = "released"
            resource["public_link_released_at"] = update.released_at
            resource["visibility"] = "public_after_review"

    if args.execute:
        write_manifest(resources, MANIFEST_PATH)
        write_results(updates, by_id)
        append_onedrive_release_log(updates)
        print(f"Updated {len(updates)} resources in {MANIFEST_PATH}")
        print(f"Wrote {RESULTS_MD} and {RESULTS_CSV}")
    else:
        print("Dry run only. Re-run with --execute to update the manifest.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
